/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesConsultoriaRouteImport } from './routes/solucoes.consultoria'
import { Route as SolucoesCrmRouteImport } from './routes/solucoes.crm'
import { Route as SolucoesDadosRouteImport } from './routes/solucoes.dados'
import { Route as SolucoesIaRouteImport } from './routes/solucoes.ia'
import { Route as SolucoesSuporteRouteImport } from './routes/solucoes.suporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesConsultoriaRoute = SolucoesConsultoriaRouteImport.update({
  id: '/solucoes/consultoria',
  path: '/solucoes/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesCrmRoute = SolucoesCrmRouteImport.update({
  id: '/solucoes/crm',
  path: '/solucoes/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesDadosRoute = SolucoesDadosRouteImport.update({
  id: '/solucoes/dados',
  path: '/solucoes/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIaRoute = SolucoesIaRouteImport.update({
  id: '/solucoes/ia',
  path: '/solucoes/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSuporteRoute = SolucoesSuporteRouteImport.update({
  id: '/solucoes/suporte',
  path: '/solucoes/suporte',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solucoes/consultoria': typeof SolucoesConsultoriaRoute
  '/solucoes/crm': typeof SolucoesCrmRoute
  '/solucoes/dados': typeof SolucoesDadosRoute
  '/solucoes/ia': typeof SolucoesIaRoute
  '/solucoes/suporte': typeof SolucoesSuporteRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solucoes/consultoria': typeof SolucoesConsultoriaRoute
  '/solucoes/crm': typeof SolucoesCrmRoute
  '/solucoes/dados': typeof SolucoesDadosRoute
  '/solucoes/ia': typeof SolucoesIaRoute
  '/solucoes/suporte': typeof SolucoesSuporteRoute
  '/solucoes': typeof SolucoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solucoes/consultoria': typeof SolucoesConsultoriaRoute
  '/solucoes/crm': typeof SolucoesCrmRoute
  '/solucoes/dados': typeof SolucoesDadosRoute
  '/solucoes/ia': typeof SolucoesIaRoute
  '/solucoes/suporte': typeof SolucoesSuporteRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/solucoes/consultoria'
    | '/solucoes/crm'
    | '/solucoes/dados'
    | '/solucoes/ia'
    | '/solucoes/suporte'
    | '/solucoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/solucoes/consultoria'
    | '/solucoes/crm'
    | '/solucoes/dados'
    | '/solucoes/ia'
    | '/solucoes/suporte'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/solucoes/consultoria'
    | '/solucoes/crm'
    | '/solucoes/dados'
    | '/solucoes/ia'
    | '/solucoes/suporte'
    | '/solucoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolucoesConsultoriaRoute: typeof SolucoesConsultoriaRoute
  SolucoesCrmRoute: typeof SolucoesCrmRoute
  SolucoesDadosRoute: typeof SolucoesDadosRoute
  SolucoesIaRoute: typeof SolucoesIaRoute
  SolucoesSuporteRoute: typeof SolucoesSuporteRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/consultoria': {
      id: '/solucoes/consultoria'
      path: '/solucoes/consultoria'
      fullPath: '/solucoes/consultoria'
      preLoaderRoute: typeof SolucoesConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/crm': {
      id: '/solucoes/crm'
      path: '/solucoes/crm'
      fullPath: '/solucoes/crm'
      preLoaderRoute: typeof SolucoesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/dados': {
      id: '/solucoes/dados'
      path: '/solucoes/dados'
      fullPath: '/solucoes/dados'
      preLoaderRoute: typeof SolucoesDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/ia': {
      id: '/solucoes/ia'
      path: '/solucoes/ia'
      fullPath: '/solucoes/ia'
      preLoaderRoute: typeof SolucoesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/suporte': {
      id: '/solucoes/suporte'
      path: '/solucoes/suporte'
      fullPath: '/solucoes/suporte'
      preLoaderRoute: typeof SolucoesSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolucoesConsultoriaRoute: SolucoesConsultoriaRoute,
  SolucoesCrmRoute: SolucoesCrmRoute,
  SolucoesDadosRoute: SolucoesDadosRoute,
  SolucoesIaRoute: SolucoesIaRoute,
  SolucoesSuporteRoute: SolucoesSuporteRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
