/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesSlugRouteImport } from './routes/solucoes.$slug'
import { Route as SolucoesConsultoriaRouteImport } from './routes/solucoes.consultoria'
import { Route as SolucoesIaRouteImport } from './routes/solucoes.ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSlugRoute = SolucoesSlugRouteImport.update({
  id: '/solucoes/$slug',
  path: '/solucoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesConsultoriaRoute = SolucoesConsultoriaRouteImport.update({
  id: '/solucoes/consultoria',
  path: '/solucoes/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIaRoute = SolucoesIaRouteImport.update({
  id: '/solucoes/ia',
  path: '/solucoes/ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/solucoes/consultoria': typeof SolucoesConsultoriaRoute
  '/solucoes/ia': typeof SolucoesIaRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/solucoes/consultoria': typeof SolucoesConsultoriaRoute
  '/solucoes/ia': typeof SolucoesIaRoute
  '/solucoes': typeof SolucoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/solucoes/consultoria': typeof SolucoesConsultoriaRoute
  '/solucoes/ia': typeof SolucoesIaRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/solucoes/$slug'
    | '/solucoes/consultoria'
    | '/solucoes/ia'
    | '/solucoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/solucoes/$slug'
    | '/solucoes/consultoria'
    | '/solucoes/ia'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/solucoes/$slug'
    | '/solucoes/consultoria'
    | '/solucoes/ia'
    | '/solucoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolucoesSlugRoute: typeof SolucoesSlugRoute
  SolucoesConsultoriaRoute: typeof SolucoesConsultoriaRoute
  SolucoesIaRoute: typeof SolucoesIaRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$slug': {
      id: '/solucoes/$slug'
      path: '/solucoes/$slug'
      fullPath: '/solucoes/$slug'
      preLoaderRoute: typeof SolucoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/consultoria': {
      id: '/solucoes/consultoria'
      path: '/solucoes/consultoria'
      fullPath: '/solucoes/consultoria'
      preLoaderRoute: typeof SolucoesConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/ia': {
      id: '/solucoes/ia'
      path: '/solucoes/ia'
      fullPath: '/solucoes/ia'
      preLoaderRoute: typeof SolucoesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolucoesSlugRoute: SolucoesSlugRoute,
  SolucoesConsultoriaRoute: SolucoesConsultoriaRoute,
  SolucoesIaRoute: SolucoesIaRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
